blueprint:
  name: Gilda Deferred Load Timer Automation
  description: Configure the deferred load start using a timer entity
  domain: automation
  author: Marcelo Matus

  input:
    deferred_load_section:
      name: Deferred Load Section
      description: Deferred Load Entities
      input:
        deferred_timer_entity:
          name: Deferred Timer
          description: This timer is used to trigger the deferred start
          selector:
            entity:
              filter:
                - domain: timer

        deferred_start_button:
          name: Deferred Start Button
          description: This button actually start the deferred load
          selector:
            entity:
              filter:
                - domain: button

trigger:
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: !input deferred_timer_entity
action:
  - action: button.press
    metadata: {}
    data: {}
    target:
      entity_id: !input deferred_start_button
